version: '3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/srv
    ports:
      - "8094:8000"
    depends_on:
      - db
    links:
      - db

volumes:
    postgres:
